#include <iostream>
using namespace std;

int main(int argc, char const *argv[])
{
    /* code */

    // sid's code
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    // sid's code2
    return 0;
}
// git learn